## Day 02: Numpy
**2-Dec-2021**

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
l1 = [1,2,3]
l2 = [2,3,4]

o = []
for i in range(len(l1)):
    o.append(l1[i]+l2[i])
print(o)

[3, 5, 7]


### Array Creation and attributes
- creating array from a sequence: 1d, 2d
- arithmetic operations on np array
- num of dim, shape, size, dtype, itemsize

In [5]:
l = [1, 3, 4, 5]

a = np.array(l)
b = np.array([1,2,3,4])
print(a, type(a))
print(b, type(b))

[1 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4] <class 'numpy.ndarray'>


In [9]:
print(a+b)
print(a*b)
print(a-b)
print(a**2) # arithmetic operations are performed elementwise

[2 5 7 9]
[ 1  6 12 20]
[0 1 1 1]
[ 1  9 16 25]


In [10]:
l2 = [[1,2,3], [4,5,6]]
a = np.array(l2)
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
print(a.shape)

(2, 3)


In [14]:
a.ndim

2

In [18]:
b = np.array([1,2,3,4])
print(b.shape, b.ndim)

(4,) 1


In [19]:
b.reshape(1,4).ndim

2

In [20]:
b.dtype

dtype('int32')

In [28]:
b = np.array([1,2,3,4], dtype=np.float32)

In [29]:
b.dtype

dtype('float32')

In [30]:
b.itemsize

4

### Creating fixed size array
- zeros, ones, empty

In [33]:
a = np.zeros((4,5), dtype=np.int32)
print(a)
print(a.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
int32


In [36]:
b = np.ones((2,5,6), dtype=np.int64)
print(b)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


In [44]:
c = np.empty((6,7)) # uninitialized
print(c)

[[1.17193869e-311 2.65673873e-311 0.00000000e+000 0.00000000e+000
  1.17194680e-311 1.17194672e-311 1.17194680e-311]
 [1.17194672e-311 0.00000000e+000 6.95321843e-310 0.00000000e+000
  0.00000000e+000 1.17191502e-311 1.17194675e-311]
 [1.17191502e-311 1.17194675e-311 0.00000000e+000 6.95321843e-310
  0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [6.95321843e-310 0.00000000e+000 0.00000000e+000 1.17192113e-311
  6.95321843e-310 1.17192113e-311 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 6.95321843e-310
  1.17192113e-311 1.17193869e-311 1.17192175e-311]
 [1.17193729e-311 6.95321842e-310 0.00000000e+000 0.00000000e+000
  1.17192113e-311 0.00000000e+000 0.00000000e+000]]


### Creating sequences of numbers
- arange, linspace 

In [45]:
a = np.arange?

In [52]:
a = np.arange(100, 4, -1).reshape(3, 2,-1)
a

array([[[100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,
          88,  87,  86,  85],
        [ 84,  83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,
          72,  71,  70,  69]],

       [[ 68,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,  57,
          56,  55,  54,  53],
        [ 52,  51,  50,  49,  48,  47,  46,  45,  44,  43,  42,  41,
          40,  39,  38,  37]],

       [[ 36,  35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,
          24,  23,  22,  21],
        [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,   9,
           8,   7,   6,   5]]])

In [53]:
a = np.linspace?

In [76]:
a = np.linspace(2,50, 100)
print(a)

[ 2.          2.48484848  2.96969697  3.45454545  3.93939394  4.42424242
  4.90909091  5.39393939  5.87878788  6.36363636  6.84848485  7.33333333
  7.81818182  8.3030303   8.78787879  9.27272727  9.75757576 10.24242424
 10.72727273 11.21212121 11.6969697  12.18181818 12.66666667 13.15151515
 13.63636364 14.12121212 14.60606061 15.09090909 15.57575758 16.06060606
 16.54545455 17.03030303 17.51515152 18.         18.48484848 18.96969697
 19.45454545 19.93939394 20.42424242 20.90909091 21.39393939 21.87878788
 22.36363636 22.84848485 23.33333333 23.81818182 24.3030303  24.78787879
 25.27272727 25.75757576 26.24242424 26.72727273 27.21212121 27.6969697
 28.18181818 28.66666667 29.15151515 29.63636364 30.12121212 30.60606061
 31.09090909 31.57575758 32.06060606 32.54545455 33.03030303 33.51515152
 34.         34.48484848 34.96969697 35.45454545 35.93939394 36.42424242
 36.90909091 37.39393939 37.87878788 38.36363636 38.84848485 39.33333333
 39.81818182 40.3030303  40.78787879 41.27272727 41.

In [75]:
(50-2)/99

0.48484848484848486

### Basic Operations
- element-wise arithmatic and comparison operation with scaler and arrays
- matrix multiplication
- +=, -=, *= etc. changes value inplace 
- Resulting matrix has a more general/ precise dtype

In [79]:
a = np.arange(1, 21)
print(a)
a < 10

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [80]:
b = np.arange(11, 31)
print(b)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [81]:
a*b

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200, 231, 264, 299,
       336, 375, 416, 459, 504, 551, 600])

In [82]:
a = a.reshape(4,5) # matrix multiplication
b = a.reshape(5,4)
a.dot(b)

array([[ 175,  190,  205,  220],
       [ 400,  440,  480,  520],
       [ 625,  690,  755,  820],
       [ 850,  940, 1030, 1120]])

In [83]:
a@b

array([[ 175,  190,  205,  220],
       [ 400,  440,  480,  520],
       [ 625,  690,  755,  820],
       [ 850,  940, 1030, 1120]])

In [84]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [85]:
a+=1

In [86]:
print(a)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]]


In [90]:
a = np.arange(1, 5, dtype=np.int32).reshape(2,-1)
b = np.arange(1, 5, dtype=np.int64).reshape(2,-1)
c = a+b
print(c, c.dtype)

[[2 4]
 [6 8]] int64


In [89]:
print(a)

[[1 2]
 [3 4]]


### Unary operations
- sum, min, max

In [116]:
a = np.arange(1, 10, dtype=np.int32).reshape(3,-1)
b = np.arange(1, 10, dtype=np.int64).reshape(3,-1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [117]:
print(np.sum(a, axis=0))
np.sum(a, axis=0).shape

[12 15 18]


(3,)

In [97]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [98]:
a.sum(0)

array([12, 15, 18])

In [99]:
a.sum(1)

array([ 6, 15, 24])

In [100]:
a.sum()

45

In [101]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
a.min(0)

array([1, 2, 3])

In [103]:
a.min(1)

array([1, 4, 7])

In [104]:
a.max(0)

array([7, 8, 9])

In [112]:
a = np.ones((2, 4, 5))
print(a)
print(a.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 4, 5)


In [115]:
print(a.sum(2).shape)
a.sum(2)

(2, 4)


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [109]:
a.mean(0)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Array indexing, slicing
- similar to list slicing
- slice is considered complete for missing slices, when fewer indices provided

In [119]:
a = np.arange(1, 21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [120]:
a[:2, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [123]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [124]:
a = np.arange(1, 51).reshape(2,5,-1)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [127]:
a[1, 3:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [128]:
a[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Stacking of arrays
hstack, vstack, concatenate

In [131]:
a = np.arange(1, 7).reshape(2,3)
b = np.arange(0, 6).reshape(2,3)
print(a, "\n", b)

[[1 2 3]
 [4 5 6]] 
 [[0 1 2]
 [3 4 5]]


In [136]:
np.hstack([a,b])

array([[1, 2, 3, 0, 1, 2],
       [4, 5, 6, 3, 4, 5]])

In [137]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 5]])

In [141]:
np.concatenate([a,b], axis=1)

array([[1, 2, 3, 0, 1, 2],
       [4, 5, 6, 3, 4, 5]])

### Making copies
- shallow copy
- deep copy

In [142]:
a = np.arange(1, 7).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [143]:
b = a # shallow copy
b[0] = 2
print(b)

[[2 2 2]
 [4 5 6]]


In [144]:
print(a)

[[2 2 2]
 [4 5 6]]


In [146]:
b = a[1] # shallow copy

In [147]:
print(b)

[4 5 6]


In [148]:
b[1:] = 0
print(b)

[4 0 0]


In [149]:
print(a)

[[2 2 2]
 [4 0 0]]


In [150]:
b = a.copy() # deep copy

In [151]:
print(a)
print(b)

[[2 2 2]
 [4 0 0]]
[[2 2 2]
 [4 0 0]]


In [152]:
b[1] = 3
print(b)
print(a)

[[2 2 2]
 [3 3 3]]
[[2 2 2]
 [4 0 0]]


### Array Indexing through integer and boolean arrays

In [157]:
a = np.arange(1, 101).reshape(20,-1)

In [159]:
print(a)
print(a.shape)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]
(20, 5)


In [160]:
idx = [1, 4, 5, 9 ] # integer based indexing, subsampling, array subsetting
a[idx]

array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [46, 47, 48, 49, 50]])

In [166]:
bool_idx = a[:,0] > 40
print(bool_idx, "\n", bool_idx.shape)

[False False False False False False False False  True  True  True  True
  True  True  True  True  True  True  True  True] 
 (20,)


In [167]:
a[bool_idx] # boolean array based subsetting

array([[ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

### I want to subset column 2,3 of my data and only those samples/rows where col2 val > 60

In [168]:
bool_idx = a[:,2] >  60
print(bool_idx)

[False False False False False False False False False False False False
  True  True  True  True  True  True  True  True]


In [169]:
a[bool_idx, 2:4]

array([[63, 64],
       [68, 69],
       [73, 74],
       [78, 79],
       [83, 84],
       [88, 89],
       [93, 94],
       [98, 99]])

### Generate Data

In [172]:
np.random.randint(1, 10, 8)

array([5, 8, 3, 4, 1, 1, 9, 9])

### Shuffle data



In [176]:
idx = np.arange(0,20)
print(idx)
np.random.shuffle(idx)
print(idx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 8 10 18  9 15  4  6  3  2 19  7 13 11  0 16  1 12 17  5 14]


In [177]:
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


In [179]:
a = a[idx]

In [180]:
a

array([[ 41,  42,  43,  44,  45],
       [ 51,  52,  53,  54,  55],
       [ 91,  92,  93,  94,  95],
       [ 46,  47,  48,  49,  50],
       [ 76,  77,  78,  79,  80],
       [ 21,  22,  23,  24,  25],
       [ 31,  32,  33,  34,  35],
       [ 16,  17,  18,  19,  20],
       [ 11,  12,  13,  14,  15],
       [ 96,  97,  98,  99, 100],
       [ 36,  37,  38,  39,  40],
       [ 66,  67,  68,  69,  70],
       [ 56,  57,  58,  59,  60],
       [  1,   2,   3,   4,   5],
       [ 81,  82,  83,  84,  85],
       [  6,   7,   8,   9,  10],
       [ 61,  62,  63,  64,  65],
       [ 86,  87,  88,  89,  90],
       [ 26,  27,  28,  29,  30],
       [ 71,  72,  73,  74,  75]])