In [1]:
import numpy as np

In [104]:
a = np.random.randint(0, 5, size=(2,2))
b = np.random.randint(0, 5, size=(3,2,2))

In [105]:
a

array([[0, 3],
       [2, 3]])

In [106]:
b

array([[[4, 4],
        [0, 4]],

       [[1, 1],
        [0, 3]],

       [[0, 3],
        [3, 4]]])

In [107]:
out = np.einsum('ij,pjk->pik', a, b)

In [108]:
out.shape

(3, 2, 2)

In [109]:
out

array([[[ 0, 12],
        [ 8, 20]],

       [[ 0,  9],
        [ 2, 11]],

       [[ 9, 12],
        [ 9, 18]]])

In [112]:
np.sum(a)

8

In [136]:
np.einsum('ij,ij->j', a, a)

array([ 4, 18])

In [117]:
x = np.random.randint(0, 5, size=(2,2))
y = np.random.randint(0, 5, size=(2,2))

In [118]:
np.einsum('ij,jk->ik', x, y)

array([[18, 18],
       [ 3,  4]])

In [124]:
result = 0 #np.zeros((2,))
for i in range(2):
#     for k in range(2):
#         for j in range(2):
#             result[i, k] += x[i, j]*y[j, k]
    result += a[i, i]
            
result #diagonal elements

3

In [137]:
a

array([[0, 3],
       [2, 3]])

In [138]:
a.T

array([[0, 2],
       [3, 3]])

In [139]:
np.einsum('ij->ji', a)

array([[0, 2],
       [3, 3]])

In [140]:
b

array([[[4, 4],
        [0, 4]],

       [[1, 1],
        [0, 3]],

       [[0, 3],
        [3, 4]]])

In [142]:
b.T

array([[[4, 1, 0],
        [0, 0, 3]],

       [[4, 1, 3],
        [4, 3, 4]]])

In [141]:
np.einsum('bij->bji', b)

array([[[4, 0],
        [4, 4]],

       [[1, 0],
        [1, 3]],

       [[0, 3],
        [3, 4]]])